### ISSUE TITLE
Home assistant core

### ISSUE THREAD

**Issue by andreapazzo** [cislow970/raspberry-solar-mon#1]
Hi! I also have the Peimar inverter but the installation of my HA is core and does not support the addon. Is it possible to convert the addon into a custom_component?
Thank you

**Comment by cislow970** [comment]
Hi, I'm sorry, I don't know how to help you. The integration "https://github.com/cislow970/raspberry-solar-mon/tree/main/home_assistant" was made with Home Assistant installed in a virtual machine.

**Comment by cislow970** [comment]
Close issue
